# Docker override: Login server = service name "loginserver"
LoginHost = loginserver
LoginPort = 9014
GameserverHostname = 0.0.0.0
GameserverPort = 7777
PacketEncryption = False
RequestServerID = 1
AcceptAlternateID = True
DatapackRoot = .
ScriptRoot = ./data/scripts
MaximumOnlineUsers = 2000
AllowedProtocolRevisions = 267;268;271;273
ServerListType = Free
ServerListAge = 0
ServerListBrackets = False
ScheduledThreadPoolSize = -1
InstantThreadPoolSize = -1
ThreadsForLoading = False
DeadlockWatcher = True
DeadlockCheckInterval = 20
RestartOnDeadlock = False
EnableHardwareInfo = False
KickMissingHWID = False
MaxPlayersPerHWID = 0
CnameTemplate = (^[A-Za-z0-9]{1,16}$)
PetNameTemplate = (^[A-Za-z0-9]{1,16}$)
ClanNameTemplate = (^[A-Za-z0-9]{1,16}$)
CharMaxNumber = 7
PrecautionaryRestartEnabled = False
PrecautionaryRestartCpu = True
PrecautionaryRestartMemory = False
PrecautionaryRestartChecks = True
PrecautionaryRestartPercentage = 95
PrecautionaryRestartDelay = 60
ServerRestartScheduleEnabled = False
ServerRestartScheduleMessage = False
ServerRestartScheduleCountdown = 600
ServerRestartSchedule = 08:00
ServerRestartDays = 4
