package com.l2journey.gameserver.geoengine.navmesh;

import java.io.File;
import java.nio.file.Files;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Logger;

import com.l2journey.gameserver.model.Location;

public class NavMeshManager
{
	private static final Logger LOGGER = Logger.getLogger(NavMeshManager.class.getName());
	
	private final Map<String, NavMeshRoute> _routes = new HashMap<>();
	private final Map<String, NavMeshZone> _zones = new HashMap<>();
	
	protected NavMeshManager()
	{
		load();
	}
	
	public void load()
	{
		_routes.clear();
		_zones.clear();
		
		File dir = new File("data/navmesh");
		if (!dir.exists())
		{
			dir.mkdirs();
			return;
		}
		
		File[] files = dir.listFiles((d, name) -> name.endsWith(".geojson"));
		if (files == null) return;
		
		for (File file : files)
		{
			try
			{
				String content = new String(Files.readAllBytes(file.toPath()));
				parseGeoJson(file.getName().replace(".geojson", ""), content);
			}
			catch (Exception e)
			{
				LOGGER.warning("NavMeshManager: Error loading " + file.getName() + ": " + e.getMessage());
			}
		}
		
		LOGGER.info("NavMeshManager: Loaded " + _routes.size() + " Routes and " + _zones.size() + " Zones.");
	}
	
	private void parseGeoJson(String defaultName, String json)
	{
		// A very rudimentary string parser for the simple GeoJSON generated by AdminNavMesh or QGIS.
		// In a production env, use Jackson or Gson.
		if (json.contains("\"type\": \"LineString\"") || json.contains("\"type\":\"LineString\""))
		{
			NavMeshRoute route = new NavMeshRoute(defaultName);
			extractCoordinates(json, route);
			_routes.put(defaultName, route);
		}
		else if (json.contains("\"type\": \"Polygon\"") || json.contains("\"type\":\"Polygon\""))
		{
			NavMeshZone zone = new NavMeshZone(defaultName);
			extractCoordinates(json, zone);
			_zones.put(defaultName, zone);
		}
	}
	
	private void extractCoordinates(String json, Object target)
	{
		int coordStart = json.indexOf("\"coordinates\"");
		if (coordStart == -1) return;
		
		int bracketStart = json.indexOf("[", coordStart);
		int bracketEnd = json.lastIndexOf("]");
		if (bracketStart == -1 || bracketEnd == -1) return;
		
		String coordBlock = json.substring(bracketStart, bracketEnd);
		
		// Extract [x, y, z] segments
		String[] segments = coordBlock.split("\\[");
		for (String segment : segments)
		{
			if (!segment.contains(",")) continue;
			
			String clean = segment.replaceAll("\\]", "").replaceAll("\\r", "").replaceAll("\\n", "").trim();
			if (clean.endsWith(","))
			{
				clean = clean.substring(0, clean.length() - 1);
			}
			
			String[] vals = clean.split(",");
			if (vals.length >= 2)
			{
				try
				{
					int x = Integer.parseInt(vals[0].trim());
					int y = Integer.parseInt(vals[1].trim());
					int z = vals.length >= 3 ? Integer.parseInt(vals[2].trim()) : -3000;
					
					Location loc = new Location(x, y, z);
					if (target instanceof NavMeshRoute)
					{
						((NavMeshRoute) target).addPoint(loc);
					}
					else if (target instanceof NavMeshZone)
					{
						((NavMeshZone) target).addPoint(loc);
					}
				}
				catch (NumberFormatException e)
				{
					// Ignore malformed coordinate
				}
			}
		}
	}
	
	public NavMeshRoute getRoute(String name)
	{
		return _routes.get(name);
	}
	
	public NavMeshZone getZone(String name)
	{
		return _zones.get(name);
	}
	
	public static NavMeshManager getInstance()
	{
		return SingletonHolder.INSTANCE;
	}
	
	private static class SingletonHolder
	{
		protected static final NavMeshManager INSTANCE = new NavMeshManager();
	}
}
